[features]
seeds = false
skip-lint = false
[programs.Localnet]
architects = "9xsHhKFyrUM5qYUHJzNhKtWzwbyo1UFythXmjKzTfVCM"

[registry]
url = "https://registry.solana.com"

[provider]
cluster = "localnet"
wallet = "/Users/warly/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
