[features]
seeds = false
skip-lint = false
[programs.devnet]
architects = "3mE2UAhuJxCbcHBCM4gFeWkJheDFw2q9iDykf3S9RDwx"
dispenser = "29Phfb8pDz2DifXVafuDHFFmg6MrcFKCGEbQXmjoSGWL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/warly/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
